### ISSUE TITLE
[bug] file access blocking does not reverse

### ISSUE THREAD

**Issue by ghost** [DavidXanatos/priv10#10]
- app v 0.1g
- W 10 Pro x_64 v 1809 b 1776.379
___
Having used the app switch to disable `SearchUI.exe` the action/settings could not be reversed in the app's UI  and the binary remained inaccessible until manually having removed the respective security descriptor.

Not sure whether bears any relevance but it would that be a typo:

`SID_Worls` as opposed to `SID_World`?

**Comment by DavidXanatos** [comment]
the typo in question is only the name of the SID not its value so while not pretty it should not be an issue. 
the relevant value is: public static string SID_World = "S-1-1-0";

I will check he file restore feature i remember that i also noticed that sometimes it failed but i couldn't pinpoint the reason as it was semi random.

**Comment by DavidXanatos** [comment]
should be fixed on the new build 0.50
