### ISSUE TITLE
[bug] empty connection log after boot

### ISSUE THREAD

**Issue by ghost** [DavidXanatos/priv10#11]
- app v 0.1g
- W 10 Pro x_64 v 1809 b 1776.379
___
with the below settings the connection log is empty upon boot. Switching the filter mode to white the connection logs starts showing

![Annotation 2019-03-16 220503](https://user-images.githubusercontent.com/13611490/54481673-9dd2a000-482f-11e9-92d7-b858dd0e2939.png)

**Comment by DavidXanatos** [comment]
the log should be loaded asynchroniusly after startup i wil test if that works or has an issue.

**Comment by ghost** [comment]
meantime updated to

- app v 0.1**h**
- W 10 Pro x_64 v **1903** b **18362.116**

and the issue is still present

**Comment by DavidXanatos** [comment]
is it still present in the new 0.50 build)
