### ISSUE TITLE
Access with password or pin slowly

### ISSUE THREAD

**Issue by gianvi97** [DavidXanatos/priv10#12]
Hi,
I have a problem: I have enabled all the options in the program. Now, when I access the PC with pin or password, the bar for inserting the pin takes some time as once the pin has been inserted and pressed enter, this is not received instantaneously. This did not happen before. What option can this problem be linked to?
Thank you_

**Comment by DavidXanatos** [comment]
probably something with disabling M$ accounts

**Comment by DavidXanatos** [comment]
since there is no more  feedback I'll close this issue
