### ISSUE TITLE
(bug) Group policy settings for MSDT and IE CEIP

### ISSUE THREAD

**Issue by CarlosMerc** [DavidXanatos/priv10#14]
Your settings seem to point to registry for these 2 which has confusing meanings. When pressed via your program, both of these are actually enabled, showing up in group policy.

The correct Group policy settings for the following are:
Under Admin templates, system, troubleshooting and diagnostics, Microsoft Support Diagnostic Tool
*Microsoft Support Diagnostic Tool: Turn on (MSDT) interactive communication with the support provider. <--- disable

Under Admin templates, windows components, Internet explorer:
*Prevent participationin the Customer Experience Improvement Program (CEIP) <------ enabled

**Comment by Thdub** [comment]
Yes, both settings have misleading names/registry value, as I pointed out on [MDL](https://forums.mydigitallife.net/threads/private-winten-open-source-windows-10-privacy-tool-with-built-in-firewall.78651/page-2#post-1506415). It's clear when reading the GPedit description : 
IE CEIP: "Prevent CEIP for internet explorer"must be "enabled".
MSDT: "if you disable this policy setting, MSDT cannot run in support mode, and no data can be collected or sent to the support provider." 

Then, checking on getadmx.com:
https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.InternetExplorer::SQM_DisableCEIP
DisableCustomerImprovementProgram should be set to "Enabled"
Enabled Value=0 
  
(https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.MSDT::MsdtSupportProvider)
DisableQueryRemoteServer should be set to "Disabled" 
Disabled Value=0

quite confusing...

**Comment by DavidXanatos** [comment]
will be fixed in the next build > 0.50b
