### ISSUE TITLE
Not working with latest Win 10 update

### ISSUE THREAD

**Issue by ErAs007** [DavidXanatos/priv10#15]
Not working with latest Win10 update. Won't even start. 
Worked fine prior to that.

**Comment by ghost** [comment]
Except for https://github.com/DavidXanatos/priv10/issues/16 and https://github.com/DavidXanatos/priv10/issues/11 it works for me on this node

- app v 0.1h
- W 10 Pro x_64 v 1903 b 18362.116

**Comment by DavidXanatos** [comment]
should be fixed in the new build 0.50
