### ISSUE TITLE
Some workarounds for v0.60

### ISSUE THREAD

**Issue by CHEF-KOCH** [DavidXanatos/priv10#21]
[v0.60](https://github.com/DavidXanatos/priv10/releases/tag/v0.60) broke a lot for me. One example, I could not even open the app without getting a .NET Framework error.

I did an upgrade (no fresh "installation"). And I found out that, for whatever strange reasons the debug files causing the problems.

So if someone else has an issue just remove:
* `PrivateWin10.pdb`
* `LocalPolicy.pdb`
* `QLicense.pdb` (_optional_)

To workaround the .NET Framework error at the beginning I removed msvcp140.dll & vcruntime140.dll in the x64 folder and the app started.

Apparently other things are broken too. Can you tag your release as beta until, let's say we are hitting v1.0? I think more tests are needed for the new changes.

Thanks.

**Comment by DavidXanatos** [comment]
That sounds really strange, do you have MSCV2017 runtime installed on your system?
without the msvcp140.dll & vcruntime140.dll  on the system starting priv10 from the console should log errors like: 

Starting Network Monitor...
Failed to initialized NetworkMonitorETW
Starting Dns Inspector...
Failed to initialized DnsInspectorETW

Do you get these?

What else is broken?

**Comment by CHEF-KOCH** [comment]
I use [this one](https://github.com/abbodi1406/vcredist), basically a repack with all latest C+ redistributable runtimes.

- I can't install the service anymore, I click on it get the popup to restart the app as admin (nothing happens) [but the "Install Service (priv10)" checkbox is then selected.
- It's impossible for me to click on the firewall icon.

![ceecc](https://user-images.githubusercontent.com/727123/69905606-62c0ce80-13b6-11ea-9440-9f2d33c5cb06.png)

I try to change some things and report back.

**Comment by DavidXanatos** [comment]
Close all instances of PrivateWin10.exe and check in the task manager if all are really closed, and check with a task manager that really all are closed. Probably when removing the service the process did not terminate and this lives the service manager in a undefined state you cant create a new service with the used name but when trying to stop it it reports as already removed. 

Terminating the hand process should solve the issue.

From the log I see that the UI can not connect to the engine probably for the same reason as the hand service is blocking the pipe name used by the engine thread to communicate.

**Comment by DavidXanatos** [comment]
I have released a bug fixed build: https://github.com/DavidXanatos/priv10/releases/tag/v0.60.1

Was a hang process the cause of your issues?

From now on I will do a pre-release first and a week later a normal release, but that to be effective requires courageous people to install the pre-release and provide feedback ;)

And I will look into providing an installer/updater soon, as it seams at least one otehr user had an issue when updating the service as well.

**Comment by CHEF-KOCH** [comment]
Thanks, v0.60.1 works as expected. 

> Was a hang process the cause of your issues?

Yeah, indeed it was, I was checking the Windows logs and I saw the process took very long to execute some things. 

I'm closing here because the reported issues are all resolved with 0.60.1. 🥇
