### ISSUE TITLE
v0.60 unusable

### ISSUE THREAD

**Issue by ghost** [DavidXanatos/priv10#23]
* on a W10 Pro x_64 v1909 node the app's firewall implementation blocks all outbound traffic, never mind which setting is applied.

* the service does not stop (unresponsive)

![Annotation 2019-11-30 125041](https://user-images.githubusercontent.com/13611490/69900238-dcca6680-1368-11ea-9b70-e1838b3f9687.png)

* firewall rules are not being deleted

**Comment by DavidXanatos** [comment]
you can always termiateterminate the process form taskmanager or from an elevated command prompt with taskkill /IM PrivateWin10.exe /F

**Comment by DavidXanatos** [comment]
I have testes the filtering mode settings in a 1909 VM and for me it works fine.
Note that it only can change these settings when the engine is running, the hang process from your second issue was probably the culpret.

about firewall rules, after testing in the VM I noticed that when trying to delete a rule the client would dead lock. after some investigation it seams there was an issue when runnign without using the windows event log. but this issue would only show when running not as service and never had ran as service.

anyhow i have fxed that and a few more minor details, here is a bugfixed build: https://github.com/DavidXanatos/priv10/releases/tag/v0.60.1

**Comment by ghost** [comment]
service is still unresponsive (hangs) with v0.60.1

**Comment by ghost** [comment]
Plus it crashes

> Problem signature
> Problem Event Name:	CLR20r3
> Problem Signature 01:	PrivateWin10.exe
> Problem Signature 02:	0.60.1.0
> Problem Signature 03:	a4293446
> Problem Signature 04:	System.Core
> Problem Signature 05:	4.8.4042.0
> Problem Signature 06:	5d7a9e8f
> Problem Signature 07:	b82
> Problem Signature 08:	4d
> Problem Signature 09:	System.InvalidOperationException
> OS Version:	10.0.18363.2.0.0.256.48
> Locale ID:	2057
> Additional Information 1:	9a7d
> Additional Information 2:	9a7d48c81cb9ad9d4a26f901bbba16a3
> Additional Information 3:	f987
> Additional Information 4:	f98776ceebca83838bf63f960b4c4756
> 
> Extra information about the problem
> Bucket ID:	9204781192ab6011810e60d0a8b1b923 (1229026197618407715)
