### ISSUE TITLE
[Feature Request] Block domains or IP's from Query Log via right-click

### ISSUE THREAD

**Issue by CHEF-KOCH** [DavidXanatos/priv10#25]
This one is a minor improvement for the app usability.

## Current behavior
You can't right-click in the "Query Log" window. You only can click on the entries and use "CTRL/Strg + C" to copy the whole line including "Time Stamp" etc. This is not optimal, because you need to remove the "useless" information for the "Blacklist" _manager_ first, otherwise the firewall will not recognize the entries.

## Idea
It would be nice to get an option to right-click on domains or/and IP's in the "Query Log" window to block those entries. They should then be listed under "Blacklist".

It also could be expanded to import/export entries from a .txt file.

## Why?
This way you do not need to manually write the domain's/IP's down and then go all they way to the "Blacklist" windows to copy them into it.

**Comment by DavidXanatos** [comment]
Yea that sounds quite useful I will add a context menu to the DNS log panel with options:
blacklist
whitelist
copy host name
copy ip address

thanks for the suggestion

**Comment by DavidXanatos** [comment]
added in build 0.65a
