### ISSUE TITLE
Support for german umlauts needed

### ISSUE THREAD

**Issue by uDEV2019** [DavidXanatos/priv10#27]
For a german translation it is need to support umlauts ( ü / ä / ö / ß ).

**Comment by DavidXanatos** [comment]
have you tried to save the translation.ini with utf8 encoding?

**Comment by uDEV2019** [comment]
translation.ini integrated in Build v0.65.1 comes by default as UTF-8, so i saved the translation.ini as UTF-8. Screenshot as proove.

![screen](https://user-images.githubusercontent.com/51911097/70737128-1f4d5500-1d12-11ea-8163-3f2bb7b36bc8.png)

**EDIT**
i've also used the latest translate.cs from sources, because there are many strings missing in translation.ini from Build v0.65.1. But even the latest translate.cs do not have all strings that a full translation is possible.

**Comment by maboroshin** [comment]
I'm not sure, but is it a multibyte character handling problem?

Japanese saved in UTF-8 is also garbled.

**Comment by uDEV2019** [comment]
First i thought Build 0.56.2 fixes the problem because of the last line in changelog, but thats only for the misspelled english lines in translate.cs.

Too bad for us :smile:

**Comment by uDEV2019** [comment]
Build 0.70 added many new strings, but the problem with german umlauts got not fixed.

**Comment by DavidXanatos** [comment]
I know, I have to look into how to fix that as i'm loading the ini strings using native windows calls.

**Comment by DavidXanatos** [comment]
![image](https://user-images.githubusercontent.com/3890945/70852659-5a7f8d80-1ea4-11ea-8478-0debcac2f933.png)

for me it works just saving he translation.ini using notepad 2.0 
so the issue must be with how you save the ini file

check out my demo file: "Füll Äccöss" LOL
[Translation.zip](https://github.com/DavidXanatos/priv10/files/3964144/Translation.zip)

**Comment by uDEV2019** [comment]
i'm using Notepad++ and saved the file as utf-8.
Your file is saved as ANSI, that is atypical if you translate these times.

Saved the file with ansi-coding and its working, proof:
![priv10](https://user-images.githubusercontent.com/51911097/70854508-295f8700-1ebd-11ea-90ed-e43c93fb3ab4.png)

Except the fact, as posted in the already closed issues about missing or not recognized strings.
Marked it in the screenshot. Cancel Button at first start is an example for not beeing recognized if lbl_cancel got translated.

**Comment by maboroshin** [comment]
I also confirmed that there was no problem with ANCI.

**Comment by uDEV2019** [comment]
Translated the newest strings, as supplied with 0.71
![trans071](https://user-images.githubusercontent.com/51911097/70936376-728d1380-2042-11ea-8cca-39fe40d8481f.png)

Still missing strings. Please add them to translate.cs

**Comment by CHEF-KOCH** [comment]
Please do not translate everything 1:1, I see this very often and this is so wrong. 

Technical products like Firewalls have a "tech slang" and this should not be translated nor "germanized". 

No one actually says" Operation Status". This is simply "Programm Status", "Status" or "Priv 10 Status".

I hope I can see the translation before it gets submitted.

**Comment by uDEV2019** [comment]
@CHEF-KOCH I know what i have to translate and what should left behind.

If you want to see translations before they get submitted, you are free to provide translated strings on your own. As you can see, there is not information before the release to incorporate new strings in the translation. The translator sees it and reacts on it. No more, no less.

**Comment by uDEV2019** [comment]
maybe some day we are getting rid off ansi...
