### ISSUE TITLE
missing or not recognized strings (for translating)

### ISSUE THREAD

**Issue by uDEV2019** [DavidXanatos/priv10#29]
following strings are missing (primarily) or not recognized if translated
- Operation Status
- Windows Firewall
- Firewall status:
- Rule Guard:
- Privacy Option
- Tweak Guard:
- Privacy Log
- TweakManager loaded X entries
- PrivateWin10 Process Startet, Mode X
- ProgramList loaded X entries
- priv10 Service starting
- priv10 Service stoppen...
- Show All Columns
- Disable Sorting
- Ico

For now i found the above entries. possibly more missing or not recognized.

**Comment by DavidXanatos** [comment]
I know and it should be fixed in the build 0.70 :)

**Comment by DavidXanatos** [comment]
except the log entries they are a but to many to localize all of them, and they are more for debugging.

I will add some better content for the overview window showing the relevant entries localized like 
a list of chamged rules
a lost of undone tweaks
etc
and hide the debug log a bit.

**Comment by uDEV2019** [comment]
my above list based upon build 0.70
