### ISSUE TITLE
Priv10 doesn't launch when Windows Defender Firewall service is disabled

### ISSUE THREAD

**Issue by duttyend** [DavidXanatos/priv10#3]
Dear Xanatos,

First of all, thank you so much for making such great software (I'm a big fan of WuMgr !) !

I use simplewall by Henry++ so the firewall management part of Priv10 is not useful in my case, and I noticed that Priv10 doesn't start when Windows Defender Firewall (mpssvc) service is disabled.

Could you please enable it to launch when the firewall service is disabled so we can use the privacy tweaks anyway ?

Best regards

**Comment by DavidXanatos** [comment]
I will look into it, that must be possible.

**Comment by DavidXanatos** [comment]
its easy will be fixed in the next release
