### ISSUE TITLE
[Feature Request]Incoming Rules popup agreement

### ISSUE THREAD

**Issue by whismerhill** [DavidXanatos/priv10#33]
Hi
nice piece of software you have there

Is there a way to configure private win10 to have popups with the ability to allow or disallow new rules creations  when some other program attempts to insert their own rules in the firewall
Currently and as far as I know you can only deny them altogether or get notifications about them ?

mostly it's steam games spamming rules changes
additionally is it possible to have the "source" of the asked rule change ?

For a bit more context, I installed win10 not so long ago (but kept win7 as dual boot)
and win7 had popups for incoming firewall connections
What I'd like is pretty much that behavior.
e.g. I don't want rule changes behind my back, but I don't want to forbid them altogether

IDEA : maybe it could be possible for Privatewin10 to disable the new rules by default & then provide a notification as to whether the user wants to enable them back ?

Thank you very much.

**Comment by DavidXanatos** [comment]
I can add a pop up for newly created / changed rules.

>additionally is it possible to have the "source" of the asked rule change ?
With the current mechanism (ETW monitoring) used to detect rule changes unfortunately no.
And I don't yet know of any other mechanism for that.

>IDEA : maybe it could be possible for Privatewin10 to disable the new rules by default & then provide a notification as to whether the user wants to enable them back ?

That is definitely doable, I'll add that to my todo.

**Comment by whismerhill** [comment]
hi, I'm not 100% sure
but it seems changing UAC (User Account Control) to maximum level has made the popups from windows firewall on inbound connections changes come back to life.

Started a few games I hadn't started before and got popups for them.
Would need more testing than my own limited self.

**Comment by DavidXanatos** [comment]
since the version 0.75 there is also a notification pop up for new 3rd party rules with the option to approve or deny them
