### ISSUE TITLE
[Feature Request]Legend for colors

### ISSUE THREAD

**Issue by whismerhill** [DavidXanatos/priv10#34]
hello,
simply put can we have a legend somewhere to explain the meanings of the colors in Firewall rules
e.g. orange, pink...
(grayed out is self explanatory since all those rules are disabled although that could be in a legend as well)

Thanks for the awesome program.

**Comment by CHEF-KOCH** [comment]
The colors represent the "access" status. 

* Green = Full Access (application isn't blocked)
* Yellow = Custom (several rules for same app)
* Red = Fully blocked
* White = Unconfigured, no rules are currently applied.
* Blue = LAN traffic only is allowed

**Comment by whismerhill** [comment]
Thanks for the reply
I wasn't looking at this screen but the firewall rules : 
https://prnt.sc/qeyt6j

**Comment by CHEF-KOCH** [comment]
* Blue = HTTP (Port 80 and 443)
* Pink = UDP Sockets
* Orange = TCP Client
* Dark orange = TCP Server 

You see it under "Open Sockets" (the drop down menu) this represents the rules status.

**Comment by whismerhill** [comment]
Thanks.
