### ISSUE TITLE
Slight Issue with software installations & random temporary executables

### ISSUE THREAD

**Issue by whismerhill** [DavidXanatos/priv10#37]
Hi
there is workarounds so it's not a huge issue
some software installs/setups will create randomly placed (in temporary directories) executables for their installation procedure and will cancel immediately if they don't have internet access

YES, I agree : what were they thinking ? LOL

Alas the situation exist, solution is to either launch the temp executable yourself if it still exists,
OR if it does not (software deleted it before terminating itself) then solution is to temporarily open the firewall outbound .... 

So unless you have a magic idea to deal with those situations (I don't LOL)
I think it would be great if we could have 
"Open Internet for x minutes" or something like that
directly from rightclicking the icon, along the two existing options of "Block Internet" & "Exit"

Again, thank you very much for this piece of software.

**Comment by DavidXanatos** [comment]
Yea that may be needed since we could have block rules for all the unwanted stuff in-place already that may be safe enough to add it this way.

although may be one could fine a better approach, like making a temporary global rule for the IP the tool tried to access, although that would fail if it tries to access multiple once... hmm...

**Comment by DavidXanatos** [comment]
You can with the 0.8x line of builds switch the firewall from Whitelist mode (that is block all not explicitly allowed), to Blocklist mode (allow new unknown things to access the internet).
I think this is a good solution, what I should add would be a timer to return to Whitelist though

**Comment by whismerhill** [comment]
> You can with the 0.8x line of builds switch the firewall from Whitelist mode (that is block all not explicitly allowed), to Blocklist mode (allow new unknown things to access the internet).
> I think this is a good solution, what I should add would be a timer to return to Whitelist though

the timer is a great idea 👍
