### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by DN69** [DavidXanatos/priv10#38]
double-click in "Connection_Notification_Window" causes MS .NET_Framework exception :

![Connection_Notification_Window__MS NET_Framework_Exception(on mouse doubleclick on row)](https://user-images.githubusercontent.com/45093987/72677467-0ff1c200-3a9d-11ea-9563-6aa9702f419d.png)

************** Text výjimky **************
System.NullReferenceException: Odkaz na objekt není nastaven na instanci objektu.
   v PrivateWin10.App.TrayAction(Object sender, TrayEventArgs args) v F:\Projects\.......\App.xaml.cs:řádek 492
   v System.Windows.Forms.NotifyIcon.OnDoubleClick(EventArgs e)
   v System.Windows.Forms.NotifyIcon.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   v System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   v System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by DavidXanatos** [comment]
https://github.com/DavidXanatos/priv10/releases/tag/v0.75b
