### ISSUE TITLE
This control cannot be selected

### ISSUE THREAD

**Issue by kekukui** [DavidXanatos/priv10#45]
![image](https://user-images.githubusercontent.com/20834957/79164972-2cf21480-7db0-11ea-911c-7281254d725a.png)

**Comment by DavidXanatos** [comment]
Yes, that is because it is disabled, if you enable the DNS functionality in settings this control will get enabled.

**Comment by kekukui** [comment]
> **if you enable the DNS functionality in settings this control will get enabled**

If disabled, the app should display this notice when you click on the icon

**Comment by DavidXanatos** [comment]
> 
> 
> > **if you enable the DNS functionality in settings this control will get enabled**
> 
> If disabled, the app should display this notice when you click on the icon

Yea that may be nicer I will add that, thanks
