### ISSUE TITLE
Local Security Authority Process : Select Service ?

### ISSUE THREAD

**Issue by whismerhill** [DavidXanatos/priv10#46]
hi,
I tried searching and found nothing

it's the only new connection popup with a "Select Service" Prompt

which I don't really know what it relates to :

the options are Kelso , SamSS , VaultSvc

I have devised that it sometimes go fetch certificates online, so I think I should let him do its thing but never know which of the service to choose.

Thanks.

PS: love the 0.75 update, thank you very much.

**Comment by DavidXanatos** [comment]
This happens when more than one service is hosted in a svchost.exe instance, than windows doesn't provide information which of the hosted services issued the blocked request.

in which case it shows a list of all services hosted in that instance for the user to pick one.

**Comment by whismerhill** [comment]
it's lsass.exe though but alright
