### ISSUE TITLE
custom window, default improvement

### ISSUE THREAD

**Issue by whismerhill** [DavidXanatos/priv10#53]
When the software is configured in whitelisting mode,
 the custom window could default to "allow" which would save a few clicks
As their is basically no reason to "block the connection" since you could instead
use the "BLOCK ACCESS" rule or just ignore it which will block the connection anyway in whitelisting mode

Thanks.

**Comment by DavidXanatos** [comment]
I think there are two things to consider,
first I don't want users accidentally giving access to something.

Second there are cases where you may want to switch to blacklist mode as its more expedient when installing software that creates a lot of temp files that need internet access.
During that you don't want software on you system that was supposed to be blocked gaining access to the internet.

So its advisable to create bock rules even when in white listing mode.

**Comment by whismerhill** [comment]
indeed you can & should create block rules even in white listing mode I agree
but then I would just use the easier : "BLOCK ACCESS" profile
the amount of times where one needs a custom rule to block access, must be extremely rare ?

also as far as accidental giving access, FULL ACCESS is much easier and quicker to give 

Anyways, was just my 2 cents

**Comment by whismerhill** [comment]
#51 
I guess if we get more profiles, this becomes not as much needed, so closing this.
