### ISSUE TITLE
Notifications Window Woes

### ISSUE THREAD

**Issue by Mrnofish** [DavidXanatos/priv10#57]
I've been experiencing the following problem with the Notifications Window:

- Both position and size reset whenever a new notification is triggered, even while editing rules
- The window stays on top at all times, even while editing rules, so you can't see most of the Rule Editing Dialog
- Slowness and unresponsiveness peaks while editing rules

**Comment by DavidXanatos** [comment]
mostly fixed in current pre release build the always on top wil be fixed in tne next build
