### ISSUE TITLE
0.82b "err on lbl_control" on mouseover  the redlight  icon

### ISSUE THREAD

**Issue by whismerhill** [DavidXanatos/priv10#65]
in 0.82b mousing over the redlight  icon
(which is above the cogwheels/settings icon)
shows
"err on lbl_control"
![Screenshot_46](https://user-images.githubusercontent.com/17818248/96336297-0bcff080-107f-11eb-913b-56e5ed668e0a.png)

**Comment by DavidXanatos** [comment]
thx will be fixed in next build
