### ISSUE TITLE
Can't activate the Firewall Option

### ISSUE THREAD

**Issue by ChingghisKhan** [DavidXanatos/priv10#66]
Hi, in Ver. 0.8, the firewall option is greyed out. In Ver. 0.1 it works.
![19-10-2020 04-24-16](https://user-images.githubusercontent.com/13459357/96395932-36789100-11c6-11eb-810d-7bf2f9fa3516.png)

**Comment by ChingghisKhan** [comment]
![19-10-2020 04-49-28](https://user-images.githubusercontent.com/13459357/96396095-a0913600-11c6-11eb-9325-4a20e3cffbe2.png)

**Comment by DavidXanatos** [comment]
These errors indicate that the core/engine process is not running.
Try unchecking and checking again the option "Dienst Installieren"

**Comment by ChingghisKhan** [comment]
Hi David,

 

Thanks a lot for fast response.

 

Now, it looks slightly different, but the service can’t be started.

I also tried un-install and new install without success.

 

My System: i5-10400F, 32GB RAM, 1TB M2 SSD, Windows 10_2004 with all the latest updates.

 



 

 



 

Von: DavidXanatos [mailto:notifications@github.com] 
Gesendet: Montag, 19. Oktober 2020 09:08
An: DavidXanatos/priv10
Cc: Chighisskhan; Author
Betreff: Re: [DavidXanatos/priv10] Can't activate the Firewall Option (#66)

 

These errors indicate that the core/engine process is not running.
Try unchecking and checking again the option "Dienst Installieren"

**Comment by DavidXanatos** [comment]
Try one of the newer builds 0.83 for example

**Comment by DavidXanatos** [comment]
ah sorry i mean 0.82b

**Comment by ChingghisKhan** [comment]
Thanks, will try and report

⁣Get BlueMail for Android ​

**Comment by ChingghisKhan** [comment]
I installed 0.82b, no luck – the service will not start:

 



 

Von: DavidXanatos [mailto:notifications@github.com] 
Gesendet: Montag, 19. Oktober 2020 10:12
An: DavidXanatos/priv10
Cc: Chighisskhan; Author
Betreff: Re: [DavidXanatos/priv10] Can't activate the Firewall Option (#66)

 

ah sorry i mean 0.82b

**Comment by DavidXanatos** [comment]
hmm. open an elevated command prompt and type
net start priv10

**Comment by ChingghisKhan** [comment]
Unfortunately no luck:

 



 

Von: DavidXanatos [mailto:notifications@github.com] 
Gesendet: Montag, 19. Oktober 2020 15:35
An: DavidXanatos/priv10
Cc: Chighisskhan; Author
Betreff: Re: [DavidXanatos/priv10] Can't activate the Firewall Option (#66)

 

hmm. open an elevated command prompt and type
net start priv10

**Comment by DavidXanatos** [comment]
what was the error message?

**Comment by ChingghisKhan** [comment]
I just saw that the screen-shots are not visible when I reply to the mail from Outlook.
![error](https://user-images.githubusercontent.com/13459357/96477822-3bc1f400-1237-11eb-83e6-133656a3a8b0.png)
System error 1067
Process endet unexpected

**Comment by DavidXanatos** [comment]
Hmm... ok strange... that indicates a crash when loading...
please try the folowing


Open an elevated command prompt, navigate to the priv10 instalation directory and execute PrivateService.exe -engine that will start the service attached to the console and print debug output to it.
probably it will end in a crash as well, then please send me the console output.

**Comment by ChingghisKhan** [comment]
Translations:

Unbehandelte Ausnahme  - Unhandled exception

 

Das System kann die angegebene Datei nicht finden   - The system can not find the stated file

 

 

 

C:\Programme\privatewin10>PrivateService.exe -engine

 

C:\Programme\privatewin10>Config Directory: C:\ProgramData\PrivateWin10

Log: PrivateWin10 Service Process Started, Mode Engine.

Engine Thread Running

Initializing app manager...

Loading program list...

Starting firewall monitor...

Starting firewall guard...

Loading Windows Firewall rules...

Assigning Firewall rules...

 

Unbehandelte Ausnahme: System.IO.FileNotFoundException: Das System kann die angegebene Datei nicht finden. (Ausnahme von HRESULT: 0x80070002)  

   bei Windows.ApplicationModel.Package.get_InstalledLocation()

   bei MiscHelpers.AppManager.GetAppResourceStr(String resourcePath)

   bei PrivateService.App.GetResourceStr(String resourcePath)

   bei PrivateWin10.Program.GetDescription()

   bei PrivateWin10.Program..ctor(ProgramID progID)

   bei PrivateWin10.ProgramList.AddProgram(ProgramID progID)

   bei PrivateWin10.Priv10Engine.LoadFwRules()

   bei PrivateWin10.Priv10Engine.Run()

   bei PrivateService.App.Main(String[] args)

 

Von: DavidXanatos [mailto:notifications@github.com] 
Gesendet: Montag, 19. Oktober 2020 18:38
An: DavidXanatos/priv10
Cc: Chighisskhan; Author
Betreff: Re: [DavidXanatos/priv10] Can't activate the Firewall Option (#66)

 

Hmm... ok strange... that indicates a crash when loading...
please try the folowing

Open an elevated command prompt, navigate to the priv10 instalation directory and execute PrivateService.exe -engine that will start the service attached to the console and print debug output to it.
probably it will end in a crash as well, then please send me the console output.

**Comment by DavidXanatos** [comment]
I see the problem... fill be fixed in the next build, its related to your UWP apps did you uninstall the MSFT store or used a tool like ntLite to remove windows components?

**Comment by ChingghisKhan** [comment]
Yes, I debloated Windows

⁣Get BlueMail for Android ​

**Comment by DavidXanatos** [comment]
Please try this build: https://github.com/DavidXanatos/priv10/releases/tag/v0.83

**Comment by ChingghisKhan** [comment]
Thanks for your fast work – this version works fine.

 

Von: DavidXanatos [mailto:notifications@github.com] 
Gesendet: Montag, 19. Oktober 2020 21:36
An: DavidXanatos/priv10
Cc: Chighisskhan; Author
Betreff: Re: [DavidXanatos/priv10] Can't activate the Firewall Option (#66)

 

Please try this build: https://github.com/DavidXanatos/priv10/releases/tag/v0.83

**Comment by DavidXanatos** [comment]
great than I can close this issue :)
