### ISSUE TITLE
Setup detected as trojan

### ISSUE THREAD

**Issue by piterq** [DavidXanatos/priv10#70]
Windows 10 20H2 (19042.572) is detecting setup file as Trojan:Win32/Wacatac.D8!ml. I'm not using any third party antivirus software (Microsoft Defender only).

**Comment by Mrnofish** [comment]
Same Windows version, using Security Intelligence 1.327.152 I get no such positive. I've just updated the Intelligence, yesterday's also didn't detect anything.

I'm scanning v0.84, which one are you?

**Comment by piterq** [comment]
Latest (0.84).
But wait, this is very strange. This was on a fresh Win 10 install (few hours ago) and now Microsoft Defender is totally OK with the same file...
