### ISSUE TITLE
Anti-DDOS, etc.

### ISSUE THREAD

**Issue by SomeRandomCats** [DavidXanatos/priv10#71]
Do you have any plans on implementing things such as protocol analysis, anti-spoofing, fragmented traffic, etc?

I am not an expert on this matter, and think you probably are, but here are some screenshots from CHX-I (long gone) and Comodo, to clarify what I mean:

![image](https://user-images.githubusercontent.com/76607628/103146354-ca9e3180-46fc-11eb-97b0-f43ec1ac3fdb.png)
![image](https://user-images.githubusercontent.com/76607628/103146361-f3262b80-46fc-11eb-9123-4c6310938a90.png)

**Comment by DavidXanatos** [comment]
There will be some new options with regard to networking in future, but what you are requesting is mostly out of the scope of the project.

**Comment by SomeRandomCats** [comment]
Thank you for the response.  Do you feel these options have no real benefit, or are they just too much trouble to implement?

**Comment by DavidXanatos** [comment]
I think in the age of many 10's of MB fast internet connections have no benefit, this things can prevent some disturbence to the connection but don't really provide a overall security improvement.
