### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zen0bit** [DavidXanatos/priv10#8]
if I make new category for program. Private WinTen close and dissapear from tasbar to..

Run again and category was saved..

**Comment by biggdick** [comment]
fck appcrash, which windows services start, for open the app?

**Comment by elgatov** [comment]
In my case category is not even saved, is there a fix in the pipeline?

**Comment by DNS** [comment]
This is also happen to me.

**Comment by DavidXanatos** [comment]
try the new build 0.50 it has many bugs fixed and less dependencies
